import type { Incident, InventoryItem, SubscriptionTier } from './types';
import { dateTime, money } from './utils';
import { VALUATION_DISCLAIMER } from './valuationService';

export function incidentTextPacket(incident:Incident,items:InventoryItem[],tier:SubscriptionTier){
  const records=incident.items.map(affected=>{const item=items.find(candidate=>candidate.id===affected.itemId);if(!item)return `ITEM RECORD UNAVAILABLE (${affected.itemId})`;
    const links=tier==='premium'&&item.comparableListings.length?item.comparableListings.map(listing=>`- ${listing.title}: ${money(listing.price,listing.currency)}\n  ${listing.url}`).join('\n'):'Not included';
    return `ITEM: ${item.itemName}\nStatus: ${affected.status.toUpperCase()}\nMake / Model: ${[item.make,item.model].filter(Boolean).join(' ')||'Not recorded'}\nSerial Number: ${item.serialNumber||'Not recorded'}\nOwner Marking: ${item.ownerMarking||'Not recorded'}\nMarking Location: ${item.markingLocation||'Not recorded'}\nDistinguishing Features: ${item.distinguishingFeatures||'Not recorded'}\nGeneral Photos: ${item.photos.length}\nSerial Photos: ${item.serialPhotos.length}\nMarking Photos: ${item.markingPhotos.length}\nDamage/Loss Photos: ${item.damagePhotos?.length??0}\nReceipts: ${item.receiptFiles.length}\nAppraisals: ${item.appraisalFiles.length}\nWarranties: ${item.warrantyFiles.length}\nOther Documents: ${item.otherFiles?.length??0}\nUser-entered value: ${money(item.userEnteredValue)}\nApproximate replacement estimate based on comparable listings: ${money(item.estimatedReplacementValueSelected)}\nEstimate range: ${money(item.estimatedReplacementValueLow)}–${money(item.estimatedReplacementValueHigh)}\nConfidence: ${item.valuationConfidence||'Not estimated'}\nChecked: ${dateTime(item.valuationCheckedAt)}\nComparable item links:\n${links}\nItem notes: ${item.notes||'None'}\nIncident item notes: ${affected.notes||'None'}\n\n${VALUATION_DISCLAIMER}`;}).join('\n\n------------------------------\n\n');
  return `PROOFVAULT INCIDENT PACKET\n\n${incident.title}\nType: ${incident.type}\nDate: ${incident.incidentDate}\nLocation: ${incident.location}\nOwner: ${incident.ownerName||'Not recorded'}\nPhone: ${incident.ownerPhone||'Not recorded'}\nEmail: ${incident.ownerEmail||'Not recorded'}\nAddress: ${incident.ownerAddress||'Not recorded'}\nPolice agency: ${incident.policeAgency||'Not recorded'}\nPolice case: ${incident.policeCaseNumber||'Not recorded'}\nInsurance: ${incident.insuranceCompany||'Not recorded'}\nClaim: ${incident.insuranceClaimNumber||'Not recorded'}\nIncident notes: ${incident.notes||'None'}\n\nAFFECTED PROPERTY\n\n${records}`;
}
