import { ChangeEvent, useState } from 'react';
import { Check, Download, FileJson, RotateCcw, Upload } from 'lucide-react';
import { loadIncidents } from '../data';
import { InventoryItem, SubscriptionTier } from '../types';
import { createBackup, parseBackup, ProofVaultBackup } from '../services/backupService';

interface BackupPanelProps { items:InventoryItem[]; tier:SubscriptionTier; onRestore:(backup:ProofVaultBackup)=>void; }
export function BackupPanel({items,tier,onRestore}:BackupPanelProps){const[pending,setPending]=useState<ProofVaultBackup>();const[message,setMessage]=useState('');const[error,setError]=useState('');
 const download=()=>{const backup=createBackup(items,loadIncidents(),tier);const blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`proofvault-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setMessage('Backup downloaded. Keep it somewhere safe.');setError('')};
 const select=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;if(file.size>10_000_000){setError('Backup file is too large.');return}try{const backup=parseBackup(await file.text());setPending(backup);setMessage('');setError('')}catch(reason){setPending(undefined);setError(reason instanceof Error?reason.message:'Backup could not be read.')}};
 const restore=()=>{if(!pending)return;onRestore(pending);setMessage(`Restored ${pending.items.length} items and ${pending.incidents.length} incidents.`);setPending(undefined);setError('')};
 return <section className="panel backupPanel"><div className="backupIntro"><FileJson/><div><h2>Local backup & restore</h2><p>Download one JSON file containing inventory, attachments, incidents, valuations, and settings. No cloud account is required.</p></div></div>{message&&<div className="inlineNotice"><Check/>{message}</div>}{error&&<div className="formError" role="alert">{error}</div>}<div className="backupActions"><button onClick={download}><Download/>Download backup</button><label><Upload/>Choose backup<input type="file" accept="application/json,.json" onChange={select}/></label></div>{pending&&<div className="restoreConfirm"><div><b>Ready to restore</b><span>{pending.items.length} items · {pending.incidents.length} incidents · exported {new Date(pending.exportedAt).toLocaleString()}</span><small>This replaces the data currently stored in this browser.</small></div><button className="dangerButton" onClick={restore}><RotateCcw/>Restore backup</button></div>}<p className="backupWarning">Backups are not encrypted. Store the file securely because it may contain photos, serial numbers, values, and incident details.</p></section>}
