import { FormEvent, useState } from 'react';
import { MapPin, Plus, Trash2 } from 'lucide-react';
import { InventoryItem, LocationRecord } from '../types';
import { uid } from '../lib/utils';

interface LocationsManagerProps{locations:LocationRecord[];items:InventoryItem[];onChange:(locations:LocationRecord[])=>void}
export function LocationsManager({locations,items,onChange}:LocationsManagerProps){const[name,setName]=useState('');const[notes,setNotes]=useState('');const[error,setError]=useState('');
 const add=(event:FormEvent)=>{event.preventDefault();const clean=name.trim();if(!clean){setError('Location name is required.');return}if(locations.some(location=>location.name.toLowerCase()===clean.toLowerCase())){setError('That location already exists.');return}onChange([...locations,{id:uid('location'),name:clean,notes:notes.trim()||undefined,createdAt:new Date().toISOString()}]);setName('');setNotes('');setError('')};
 const remove=(id:string)=>onChange(locations.filter(location=>location.id!==id));
 return <><header><p className="eyebrow green">LOCATIONS</p><h1>Where property lives</h1><p className="sub">Keep location names consistent so inventory and incident records stay easy to filter.</p></header><div className="locationLayout"><section className="panel"><h2>Saved locations</h2><div className="locationList">{locations.map(location=>{const count=items.filter(item=>item.location.toLowerCase()===location.name.toLowerCase()).length;return <div className="locationRow" key={location.id}><MapPin/><div><b>{location.name}</b><small>{location.notes||'No notes'} · {count} {count===1?'item':'items'}</small></div><button onClick={()=>remove(location.id)} aria-label={`Remove ${location.name}`} title={count?'Items keep their existing location text.':'Remove location'}><Trash2/></button></div>})}</div></section><form className="panel formSection" onSubmit={add}><h2>Add location</h2>{error&&<div className="formError" role="alert">{error}</div>}<label>Location name<input value={name} onChange={event=>setName(event.target.value)} placeholder="Workshop"/></label><label>Notes<textarea value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Address, access details, or description"/></label><button className="primary locationAdd" type="submit"><Plus/>Add location</button></form></div></>}
