import { useState } from 'react';
import { ArrowLeft, Check, ChevronRight, Clipboard, ExternalLink, FileText, Home, LockKeyhole, Package, Search, Settings, ShieldCheck, Sparkles, Tag, TriangleAlert } from 'lucide-react';
import { loadItems, loadTier, saveItems, saveTier, seedIncident } from './data';
import { InventoryItem, SubscriptionTier } from './types';
import { completenessScore } from './services/completeness';
import { VALUATION_DISCLAIMER, valuationService } from './services/valuationService';
import { dateTime, money } from './lib/utils';
import { incidentReport } from './services/exportService';

type View = 'home' | 'inventory' | 'detail' | 'incident' | 'settings';

export function App() {
  const [view, setView] = useState<View>('home');
  const [items, setItems] = useState<InventoryItem[]>(loadItems);
  const [tier, setTierState] = useState<SubscriptionTier>(loadTier);
  const [selectedId, setSelectedId] = useState('drill');
  const [loading, setLoading] = useState(false);
  const [manual, setManual] = useState('');
  const [notice, setNotice] = useState('');
  const selected = items.find(item => item.id === selectedId) ?? items[0];
  const update = (next: InventoryItem) => { const all = items.map(i => i.id === next.id ? next : i); setItems(all); saveItems(all); };
  const setTier = (next: SubscriptionTier) => { setTierState(next); saveTier(next); setNotice(`${next === 'premium' ? 'Premium' : 'Free'} demo mode enabled.`); };
  const open = (id: string) => { setSelectedId(id); setView('detail'); };
  const find = async () => { setLoading(true); const r = await valuationService.findComparableValues(selected); update({...selected, estimatedReplacementValueLow:r.estimatedReplacementValueLow, estimatedReplacementValueHigh:r.estimatedReplacementValueHigh, estimatedReplacementValueSelected:r.suggestedReplacementValue, valuationCurrency:'USD', valuationConfidence:r.confidence, valuationSourceSummary:r.sourceSummary, valuationCheckedAt:new Date().toISOString(), comparableListings:r.comparableListings, updatedAt:new Date().toISOString()}); setLoading(false); setNotice('Comparable values found and saved.'); };
  const choose = (price: number) => { update({...selected, estimatedReplacementValueSelected:price, valuationNotes:'Selected from a saved comparable', updatedAt:new Date().toISOString()}); setNotice('Selected comparable value saved.'); };
  const saveManual = () => { const value=Number(manual); if(value>0){update({...selected,userEnteredValue:value,updatedAt:new Date().toISOString()});setManual('');setNotice('Manual value saved.');} };
  const nav = (target: Exclude<View,'detail'>, label: string, icon: React.ReactNode) => <button className={view===target?'nav active':'nav'} onClick={()=>setView(target)}>{icon}<span>{label}</span></button>;
  return <div className="shell">
    <aside><div className="brand"><ShieldCheck/><b>ProofVault</b></div><p className="eyebrow">PROPERTY EVIDENCE</p>{nav('home','Overview',<Home/>)}{nav('inventory','Inventory',<Package/>)}{nav('incident','Incident',<FileText/>)}<div className="spacer"/>{nav('settings','Settings',<Settings/>)}<div className="privacy"><LockKeyhole/><div><b>Local demo</b><small>Data stays in this browser</small></div></div></aside>
    <main>{notice&&<button className="toast" onClick={()=>setNotice('')} aria-label="Dismiss notification"><Check/>{notice}</button>}
      {view==='home'&&<HomeView items={items} tier={tier} open={open}/>} {view==='inventory'&&<InventoryView items={items} open={open}/>} {view==='detail'&&<DetailView item={selected} tier={tier} loading={loading} back={()=>setView('inventory')} find={find} choose={choose} manual={manual} setManual={setManual} saveManual={saveManual} upgrade={()=>setTier('premium')}/>} {view==='incident'&&<IncidentView items={items} tier={tier}/>} {view==='settings'&&<SettingsView tier={tier} setTier={setTier}/>} 
    </main>
  </div>;
}

function PageHead({kicker,title,sub}:{kicker:string;title:string;sub:string}){return <header><p className="eyebrow green">{kicker}</p><h1>{title}</h1><p className="sub">{sub}</p></header>}
function ItemIcon({category}:{category:string}){return <div className="itemicon">{category==='Jewelry'?<Tag/>:<Package/>}</div>}
function Score({item}:{item:InventoryItem}){const s=completenessScore(item);return <div className="score"><span style={{width:`${s.score}%`}}/><small>{s.score}%</small></div>}
function ItemRow({item,open}:{item:InventoryItem;open:(id:string)=>void}){return <button className="itemrow" onClick={()=>open(item.id)}><ItemIcon category={item.category}/><div><b>{item.itemName}</b><small>{item.location} · {item.serialNumber||item.ownerMarking||'Needs identifier'}</small></div><Score item={item}/><ChevronRight/></button>}

function HomeView({items,tier,open}:{items:InventoryItem[];tier:SubscriptionTier;open:(id:string)=>void}){return <><PageHead kicker="GOOD EVENING" title="Your property, documented." sub="Keep the details that matter ready before you need them."/><div className="stats"><div><Package/><span><b>{items.length}</b>Inventory items</span></div><div><ShieldCheck/><span><b>{items.filter(i=>i.serialNumber||i.ownerMarking).length}</b>Identifiable records</span></div><div><Sparkles/><span><b>{items.filter(i=>i.estimatedReplacementValueSelected).length}</b>Value assisted</span></div></div><section className="panel"><div className="sectionTitle"><div><p className="eyebrow">RECENT INVENTORY</p><h2>Ready when it matters</h2></div><span className="tier">{tier} plan</span></div>{items.slice(0,4).map(item=><ItemRow key={item.id} item={item} open={open}/>)}</section><div className="callout"><TriangleAlert/><div><b>Incident Mode</b><p>Create a focused police and insurance packet from your documented items.</p></div><span>1 demo incident ready</span></div></>}
function InventoryView({items,open}:{items:InventoryItem[];open:(id:string)=>void}){return <><PageHead kicker="INVENTORY" title="Documented property" sub="Identifiers, evidence, and values in one place."/><div className="search"><Search/><input aria-label="Search inventory" placeholder="Search inventory"/></div><section className="panel">{items.map(item=><ItemRow key={item.id} item={item} open={open}/>)}</section></>}

interface DetailProps{item:InventoryItem;tier:SubscriptionTier;loading:boolean;back:()=>void;find:()=>void;choose:(price:number)=>void;manual:string;setManual:(value:string)=>void;saveManual:()=>void;upgrade:()=>void}
function DetailView({item,tier,loading,back,find,choose,manual,setManual,saveManual,upgrade}:DetailProps){const c=completenessScore(item);const best=item.comparableListings[0];return <><button className="back" onClick={back}><ArrowLeft/>Inventory</button><div className="detailHead"><ItemIcon category={item.category}/><div><p className="eyebrow green">{item.category}</p><h1>{item.itemName}</h1><p>{item.make} {item.model} · {item.location}</p></div><div className="scorebox"><b>{c.score}%</b><span>{c.label}</span></div></div><div className="grid"><div><section className="panel facts"><div className="sectionTitle"><h2>Identity & evidence</h2><span className="ok"><Check/>Documented</span></div><dl><div><dt>Serial number</dt><dd>{item.serialNumber||'Not recorded'}</dd></div><div><dt>Owner-applied marking</dt><dd>{item.ownerMarking||'Not recorded'}</dd></div><div><dt>Marking location</dt><dd>{item.markingLocation||'Not recorded'}</dd></div><div><dt>Condition</dt><dd>{item.condition}</dd></div></dl><p className="feedback">{c.feedback}</p></section><section className="panel valuation"><div className="valueTitle"><div className="spark"><Sparkles/></div><div><p className="eyebrow green">PREMIUM ASSIST</p><h2>Replacement Value Assist</h2></div>{tier==='premium'&&<span className="premium">PREMIUM</span>}</div>
  {item.estimatedReplacementValueSelected ? <ValuationResults item={item} best={best} choose={choose}/> : tier==='free' ? <div className="locked"><LockKeyhole/><h3>Know what replacement may cost</h3><p>Premium finds and saves comparable new, used, and refurbished listings. Manual values stay available on the free plan.</p><button className="primary" onClick={upgrade}>Upgrade demo to Premium</button></div> : <div className="empty"><Sparkles/><h3>No estimate yet</h3><p>Search mocked marketplace sources to build an approximate replacement range.</p></div>}
  <div className="actions"><button className="primary" disabled={tier==='free'||loading} onClick={find}>{loading?'Checking sources…':'Find Comparable Values'}</button>{item.estimatedReplacementValueSelected&&<button onClick={()=>choose(item.estimatedReplacementValueSelected!)}>Use this value</button>}</div><div className="manual"><input aria-label="Manual value" type="number" value={manual} onChange={e=>setManual(e.target.value)} placeholder={item.userEnteredValue?`Manual value: ${money(item.userEnteredValue)}`:'Enter manual value'}/><button onClick={saveManual}>Add manual value</button></div><div className="checked">Checked: {dateTime(item.valuationCheckedAt)}{item.valuationSourceSummary&&` · ${item.valuationSourceSummary}`}</div><p className="disclaimer">{VALUATION_DISCLAIMER}</p></section></div><aside className="side"><section className="panel"><p className="eyebrow">VALUE SUMMARY</p><div className="bigvalue">{money(item.userEnteredValue)}</div><small>User-entered value</small><hr/><div className="bigvalue">{money(item.estimatedReplacementValueSelected)}</div><small>Replacement Value Assist</small></section><section className="panel"><p className="eyebrow">DOCUMENTATION</p><p>{item.photos.length} item photo</p><p>{item.serialPhotos.length+item.markingPhotos.length} identifier photos</p><p>{item.receiptFiles.length} receipt</p><p>{item.appraisalFiles.length} appraisal</p></section></aside></div></>}

function ValuationResults({item,best,choose}:{item:InventoryItem;best?:InventoryItem['comparableListings'][number];choose:(n:number)=>void}){return <><div className="estimate"><div><small>ESTIMATED REPLACEMENT RANGE</small><b>{money(item.estimatedReplacementValueLow)} – {money(item.estimatedReplacementValueHigh)}</b><span>Selected estimate: {money(item.estimatedReplacementValueSelected)}</span></div><div className={`confidence ${item.valuationConfidence}`}>{item.valuationConfidence} confidence</div></div>{best&&<><p className="eyebrow">BEST COMPARABLE</p><div className="comparable"><div><b>{best.title}</b><small>{best.marketplace} · {best.condition} · {best.matchReason}</small></div><strong>{money(best.price)}</strong><a href={best.url} target="_blank" rel="noreferrer" aria-label="Open comparable listing"><ExternalLink/></a></div></>}{item.comparableListings.slice(1).map(x=><div className="comparable minor" key={x.id}><div><b>{x.title}</b><small>{x.marketplace} · {x.condition}</small></div><strong>{money(x.price)}</strong><button className="textBtn" onClick={()=>choose(x.price)}>Use this value</button></div>)}</>}

function IncidentView({items,tier}:{items:InventoryItem[];tier:SubscriptionTier}){const[shown,setShown]=useState(false);const report=incidentReport(seedIncident,items,tier);return <><PageHead kicker="INCIDENT MODE" title="Garage burglary" sub="Police and insurance packet · 1 affected item"/><section className="panel incident"><div><span className="status">STOLEN</span><h2>{items[0].itemName}</h2><p>Police case {seedIncident.policeCaseNumber} · Claim {seedIncident.insuranceClaimNumber}</p></div><button className="primary" onClick={()=>setShown(!shown)}><FileText/>{shown?'Hide packet':'Generate packet'}</button></section>{shown&&<section className="panel report"><div className="sectionTitle"><h2>Incident export packet</h2><button onClick={()=>navigator.clipboard.writeText(report)}><Clipboard/>Copy report</button></div><pre>{report}</pre></section>}</>}
function SettingsView({tier,setTier}:{tier:SubscriptionTier;setTier:(tier:SubscriptionTier)=>void}){return <><PageHead kicker="SETTINGS" title="Demo controls" sub="Switch plans to test both Replacement Value Assist experiences."/><section className="panel settings"><h2>Subscription status</h2><div className="segmented"><button className={tier==='free'?'selected':''} onClick={()=>setTier('free')}>Free</button><button className={tier==='premium'?'selected premiumBtn':''} onClick={()=>setTier('premium')}>Premium</button></div><p>Premium enables automatic comparable lookup, saved estimates, and marketplace links in incident exports.</p></section><section className="panel privacyPanel"><LockKeyhole/><div><h2>Privacy by default</h2><p>This web demo stores inventory locally in your browser. No account, analytics, or cloud upload is used.</p></div></section></>}
